#!/bin/bash

# Old way (brutal)
#sudo rm -rf /usr/share/themes/Mint-*
#sudo cp -R usr /

# New way
echo "Bind mounting the theme to /usr/share/themes/Mint-X..."

sudo mount --bind usr/share/themes/Mint-X /usr/share/themes/Mint-X

if [ -d ../mint-themes-gtk3 ]; then
    echo "Found mint-themes-gtk3 in parent directory. Bind mounting as well..."
    [ ! -d /usr/share/themes/Mint-X/gtk-3.0 ] && mkdir /usr/share/themes/Mint-X/gtk-3.0
    
    sudo mount --bind ../mint-themes-gtk3/usr/share/themes/Mint-X/gtk-3.0 /usr/share/themes/Mint-X/gtk-3.0
fi

read -p "Theme active. Press any key to revert..."

if [ -d ../mint-themes-gtk3 ]; then
    sudo umount /usr/share/themes/Mint-X/gtk-3.0
fi
sudo umount /usr/share/themes/Mint-X

echo "Theme deactivated. Reload applications to take effect."
exit 0
